[project]
name = "envxtract"
version = "0.1.0"
description = "Data extraction and analysis of environmental variables"
authors = [{ name = "Muhammad Shafeeque", email = "shafeequ@uni-bremen.de" }]
requires-python = ">=3.13"
dependencies = [
    "build>=1.2.2.post1",
    "geopandas>=1.1.0",
    "matplotlib>=3.10.3",
    "numpy>=2.2.6",
    "pytest>=8.4.0",
    "rasterio>=1.4.3",
    "twine>=6.1.0",
    "xarray>=2025.4.0",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.uv]
dev-dependencies = [
    "twine>=6.0.1",
    "build>=1.2.2",
    "bumpver>=2024.1125",
]
